apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::873286279749:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::873286279749:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QWILA49CMWFJ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-09T21:01:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "879"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8a8d56ce-c49b-477b-b111-befc1cab30bc
